### ISSUE TITLE
Release 0.3.4 TODO

### ISSUE THREAD

**Issue by RamiKrispin** [RamiKrispin/coronavirus#114]
- [ ] Update the vignettes with the changes
- [ ] Add refresh function to the vaccine dataset
- [ ] Deprecate the `data_refresh` function
